Migrate to Appyx for navigation
imashnake0/Animite pull request #56
Opened 2022-11-07 08:44 UTC by boswelja

[comment]: # (Replace [ ] with [x].)
- [x] Read [`CONTRIBUTING.md`](https://github.com/imashnake0/Animite/blob/be53ba4561c8ff20f588fb348965f208e301b6b8/CONTRIBUTING.md).

* Removing `compose-destinations`, which was giving me anxiety attacks, and replace it with [Appyx](https://bumble-tech.github.io/appyx/).
* Transition animations are gone, we should look into something fancy to replace them.
* We will need to rethink our approach to hiding the navigation bar, there is no obvious way to check whether we have traversed a child node in Appyx.

**Tested changes:**

App still runs.

[comment]: # (THANK YOU! ♡\(灬♥ ◡ ♥灬\))

2022-11-07 22:08 UTC, imashnake0 requested changes
Great work @boswelja, let's bring changes to the layouts in another PR and keep this focused on specifically migrating to Appyx.

A couple things that we should probably fix:
- [ ] Padding and layout of the search bar is strange.
- [ ] Hiding the navigation bar on navigating to the media page.
- [ ] Navigation from the search bar.
- [ ] Profile icon is larger.
- [ ] Navigation to details page is glitchy.
- [ ] Layout changes (`Scaffold`, etc) in a different PR.

2022-11-07 23:41 UTC, boswelja commented on app/src/main/java/com/imashnake/animite/features/MainActivity.kt
> -                Box(Modifier.fillMaxSize()) {
I did the same work with 20% less lines of code, is that not convincing enough?

2022-11-07 23:42 UTC, boswelja commented on app/src/main/java/com/imashnake/animite/features/MainActivity.kt
> -                    val searchBarBottomPadding: Dp by animateDpAsState(
I tested it and it seems to be working fine, am I missing something?

2022-11-07 23:43 UTC, boswelja commented on app/src/main/java/com/imashnake/animite/features/RootNode.kt
> +                    SearchBar(onItemClicked = { /* TODO */ })
Good catch, I forgot to add the nav call

2022-11-07 23:44 UTC, boswelja commented on app/src/main/java/com/imashnake/animite/features/RootNode.kt
> +                    transitionHandler = rememberBackstackFader()
I noticed this too, it probably has something to do with the way details are loaded in the media page. I can start making changes there if you like

2022-11-08 00:17 UTC, boswelja commented on app/src/main/java/com/imashnake/animite/features/RootNode.kt
> +                    transitionHandler = rememberBackstackFader()
Probably related: https://github.com/bumble-tech/appyx/discussions/246

2022-11-11 03:53 UTC, boswelja commented
Closing this due to blockers with Appyx

2022-11-11 03:53 UTC, closed without merging